return {
    PulseRun = {
        Id = "PulseRun",
        DisplayName = "Pulso y Silencio",
        Description = "Avanzá durante el pulso azul y quedate inmóvil durante el pulso rojo.",
        BaseDuration = 85,
        MinimumPlayers = 1,
        RewardWon = 1_200,
        Accent = Color3.fromRGB(80, 190, 255),
    },
    InkMemory = {
        Id = "InkMemory",
        DisplayName = "Memoria de Tinta",
        Description = "Memorizá el símbolo seguro y elegí la plataforma correcta.",
        BaseDuration = 75,
        MinimumPlayers = 1,
        RewardWon = 1_350,
        Accent = Color3.fromRGB(190, 90, 255),
    },
    FallingGrid = {
        Id = "FallingGrid",
        DisplayName = "Cuadrícula Inestable",
        Description = "Las plataformas desaparecen. Buscá espacio y no caigas.",
        BaseDuration = 70,
        MinimumPlayers = 1,
        RewardWon = 1_500,
        Accent = Color3.fromRGB(255, 160, 70),
    },
    GuardHunt = {
        Id = "GuardHunt",
        DisplayName = "Cacería de Sombras",
        Description = "Los corredores deben alcanzar refugios mientras los guardias intentan marcarlos.",
        BaseDuration = 80,
        MinimumPlayers = 4,
        RewardWon = 1_800,
        Accent = Color3.fromRGB(235, 75, 100),
    },
    LastPlatform = {
        Id = "LastPlatform",
        DisplayName = "Última Plataforma",
        Description = "La arena se reduce por etapas. Sobreviví hasta el final.",
        BaseDuration = 90,
        MinimumPlayers = 2,
        RewardWon = 2_000,
        Accent = Color3.fromRGB(255, 220, 80),
    },
}
