return {
    InkRifle = {
        DisplayName = "Rifle de Tinta",
        Damage = 24,
        HeadshotMultiplier = 1.55,
        FireInterval = 0.14,
        Magazine = 30,
        ReloadSeconds = 1.8,
        Range = 420,
        Pellets = 1,
        SpreadDegrees = 0.9,
        Automatic = true,
        Accent = Color3.fromRGB(0, 226, 239),
    },
    NeonSMG = {
        DisplayName = "SMG Neón",
        Damage = 16,
        HeadshotMultiplier = 1.45,
        FireInterval = 0.085,
        Magazine = 38,
        ReloadSeconds = 1.55,
        Range = 300,
        Pellets = 1,
        SpreadDegrees = 1.9,
        Automatic = true,
        Accent = Color3.fromRGB(255, 45, 145),
    },
    SplashShotgun = {
        DisplayName = "Escopeta Splash",
        Damage = 12,
        HeadshotMultiplier = 1.25,
        FireInterval = 0.75,
        Magazine = 7,
        ReloadSeconds = 2.25,
        Range = 150,
        Pellets = 7,
        SpreadDegrees = 7.5,
        Automatic = false,
        Accent = Color3.fromRGB(255, 150, 30),
    },
}
